(ns overtone-playground.samples
  (:require
   [overtone.live :refer [defsample]]))

;; This is a collection of samples also used by sonic-pi.


;; Ambient
(defsample ambi_choir "resources/samples/ambi_choir.wav")
(defsample ambi_dark_woosh "resources/samples/ambi_dark_woosh.wav")
(defsample ambi_drone "resources/samples/ambi_drone.wav")
(defsample ambi_glass_hum "resources/samples/ambi_glass_hum.wav")
(defsample ambi_glass_rub "resources/samples/ambi_glass_rub.wav")
(defsample ambi_haunted_hum "resources/samples/ambi_haunted_hum.wav")
(defsample ambi_lunar_land "resources/samples/ambi_lunar_land.wav")
(defsample ambi_piano "resources/samples/ambi_piano.wav")
(defsample ambi_sauna "resources/samples/ambi_sauna.wav")
(defsample ambi_soft_buzz "resources/samples/ambi_soft_buzz.wav")
(defsample ambi_swoosh "resources/samples/ambi_swoosh.wav")
(defsample loop_amen "resources/samples/loop_amen.wav")

;; Bass
(defsample bass_dnb_f "resources/samples/bass_dnb_f.wav")
(defsample bass_drop_c "resources/samples/bass_drop_c.wav")
(defsample bass_hard_c "resources/samples/bass_hard_c.wav")
(defsample bass_hit_c "resources/samples/bass_hit_c.wav")
(defsample bass_thick_c "resources/samples/bass_thick_c.wav")
(defsample bass_trance_c "resources/samples/bass_trance_c.wav")
(defsample bass_voxy_c "resources/samples/bass_voxy_c.wav")
(defsample bass_voxy_hit_c "resources/samples/bass_voxy_hit_c.wav")
(defsample bass_woodsy_c "resources/samples/bass_woodsy_c.wav")

;; Bass Drums
(defsample bd_808 "resources/samples/bd_808.wav")
(defsample bd_ada "resources/samples/bd_ada.wav")
(defsample bd_boom"resources/samples/bd_boom.wav")
(defsample bd_fat "resources/samples/bd_fat.wav")
(defsample bd_gas "resources/samples/bd_gas.wav")
(defsample bd_haus"resources/samples/bd_haus.wav")
(defsample bd_klub "resources/samples/bd_klub.wav")
(defsample bd_mehackit "resources/samples/bd_mehackit.wav")
(defsample bd_pure "resources/samples/bd_pure.wav")
(defsample bd_sone "resources/samples/bd_sone.wav")
(defsample bd_tek "resources/samples/bd_tek.wav")
(defsample bd_zome "resources/samples/bd_zome.wav")
(defsample bd_zum "resources/samples/bd_zum.wav")

;; Clave
(defsample clave "resources/samples/clave.wav")

;; Drums
(defsample drum_bass_hard "resources/samples/drum_bass_hard.wav")
(defsample drum_bass_soft "resources/samples/drum_bass_soft.wav")
(defsample drum_cowbell "resources/samples/drum_cowbell.wav")
(defsample drum_cymbal_closed "resources/samples/drum_cymbal_closed.wav")
(defsample drum_cumbal_hard "resources/samples/drum_cymbal_hard.wav")
(defsample drum_cymbal_open "resources/samples/drum_cymbal_open.wav")
(defsample drum_cymbal_pedal "resources/samples/drum_cymbal_pedal.wav")
(defsample drum_cymbal_soft "resources/samples/drum_cymbal_soft.wav")
(defsample drum_heavy_kick "resources/samples/drum_heavy_kick.wav")
(defsample drum_roll "resources/samples/drum_roll.wav")
(defsample drum_snare_hard "resources/samples/drum_snare_hard.wav")
(defsample drum_snare_soft "resources/samples/drum_snare_soft.wav")
(defsample drum_splash_hard "resources/samples/drum_splash_hard.wav")
(defsample drum_splash_soft "resources/samples/drum_splash_soft.wav")
(defsample drum_tom_hi_hard "resources/samples/drum_tom_hi_hard.wav")
(defsample drum_tom_hi_soft "resources/samples/drum_tom_hi_soft.wav")
(defsample drum_tom_lo_hard "resources/samples/drum_tom_lo_hard.wav")
(defsample drum_tom_lo_soft "resources/samples/drum_tom_lo_soft.wav")
(defsample drum_tom_mid_hard "resources/samples/drum_tom_mid_hard.wav")
(defsample drum_tom_mid_soft "resources/samples/drum_tom_mid_soft.wav")

;; Electric Sounds
(defsample elec_beep "resources/samples/elec_beep.wav")
(defsample elec_bell "resources/samples/elec_bell.wav")
(defsample elec_blip2 "resources/samples/elec_blip2.wav")
(defsample elec_blip "resources/samples/elec_blip.wav")
(defsample elec_blup "resources/samples/elec_blup.wav")
(defsample elec_bong "resources/samples/elec_bong.wav")
(defsample elec_chime "resources/samples/elec_chime.wav")
(defsample elec_cymbal "resources/samples/elec_cymbal.wav")
(defsample elec_filt_snare "resources/samples/elec_filt_snare.wav")
(defsample elec_flip "resources/samples/elec_flip.wav")
(defsample elec_fuzz_tom "resources/samples/elec_fuzz_tom.wav")
(defsample elec_hi_snare "resources/samples/elec_hi_snare.wav")
(defsample elec_hollow_kick "resources/samples/elec_hollow_kick.wav")
(defsample elec_lo_snare "resources/samples/elec_lo_snare.wav")
(defsample elec_mid_snare "resources/samples/elec_mid_snare.wav")
(defsample elec_ping "resources/samples/elec_ping.wav")
(defsample elec_plip "resources/samples/elec_plip.wav")
(defsample elec_pop "resources/samples/elec_pop.wav")
(defsample elec_snare "resources/samples/elec_snare.wav")
(defsample elec_soft_kick "resources/samples/elec_soft_kick.wav")
(defsample elec_tick "resources/samples/elec_tick.wav")
(defsample elec_triangle "resources/samples/elec_triangle.wav")
(defsample elec_twang "resources/samples/elec_twang.wav")
(defsample elec_twip "resources/samples/elec_twip.wav")
(defsample elec_wood "resources/samples/elec_wood.wav")

;; Glitchy Sounds
(defsample glitch_bass_g "resources/samples/glitch_bass_g.wav")
(defsample glitch_perc_1 "resources/samples/glitch_perc1.wav")
(defsample glitch_perc_2 "resources/samples/glitch_perc2.wav")
(defsample glitch_perc_3 "resources/samples/glitch_perc3.wav")
(defsample glitch_perc_4 "resources/samples/glitch_perc4.wav")
(defsample glitch_perc_5 "resources/samples/glitch_perc5.wav")
(defsample glitch_robot_1 "resources/samples/glitch_robot1.wav")
(defsample glitch_robot_2 "resources/samples/glitch_robot2.wav")

;; Guitar
(defsample guit_e_fifths "resources/samples/guit_e_fifths.wav")
(defsample guit_em9 "resources/samples/guit_em9.wav")
(defsample guit_e_slide "resources/samples/guit_e_slide.wav")
(defsample guit_harmonics "resources/samples/guit_harmonics.wav")

;; Loops
(defsample loop_3d_printer "resources/samples/loop_3d_printer.wav")
(defsample loop_amen_full "resources/samples/loop_amen_full.wav")
(defsample loop_amen "resources/samples/loop_amen.wav")
(defsample loop_breakbeat "resources/samples/loop_breakbeat.wav")
(defsample loop_compus "resources/samples/loop_compus.wav")
(defsample loop_drone_g_97 "resources/samples/loop_drone_g_97.wav")
(defsample loop_electric "resources/samples/loop_electric.wav")
(defsample loop_garzul "resources/samples/loop_garzul.wav")
(defsample loop_industrial "resources/samples/loop_industrial.wav")
(defsample loop_mehackit1 "resources/samples/loop_mehackit1.wav")
(defsample loop_mehackit2 "resources/samples/loop_mehackit2.wav")
(defsample loop_mika "resources/samples/loop_mika.wav")
(defsample loop_perc1 "resources/samples/loop_perc1.wav")
(defsample loop_perc2 "resources/samples/loop_perc2.wav")
(defsample loop_safari "resources/samples/loop_safari.wav")
(defsample loop_tabla "resources/samples/loop_tabla.wav")
(defsample loop_weirdo "resources/samples/loop_weirdo.wav")

;; Mehackit Sounds
(defsample mehackit_phone1 "resources/samples/mehackit_phone1.wav")
(defsample mehackit_phone2 "resources/samples/mehackit_phone2.wav")
(defsample mehackit_phone3 "resources/samples/mehackit_phone3.wav")
(defsample mehackit_phone4 "resources/samples/mehackit_phone4.wav")
(defsample mehackit_robot1 "resources/samples/mehackit_robot1.wav")
(defsample mehackit_robot2 "resources/samples/mehackit_robot2.wav")
(defsample mehackit_robot3 "resources/samples/mehackit_robot3.wav")
(defsample mehackit_robot4 "resources/samples/mehackit_robot4.wav")
(defsample mehackit_robot5 "resources/samples/mehackit_robot5.wav")
(defsample mehackit_robot6 "resources/samples/mehackit_robot6.wav")
(defsample mehackit_robot7 "resources/samples/mehackit_robot7.wav")

;; Misc
(defsample misc_burp"resources/samples/misc_burp.wav")
(defsample misc_cineboom"resources/samples/misc_cineboom.wav")
(defsample misc_crow "resources/samples/misc_crow.wav")

;; Percussion
(defsample perc_bell2 "resources/samples/perc_bell2.wav")
(defsample perc_bell "resources/samples/perc_bell.wav")
(defsample perc_door "resources/samples/perc_door.wav")
(defsample perc_impact1 "resources/samples/perc_impact1.wav")
(defsample perc_impact2 "resources/samples/perc_impact2.wav")
(defsample perc_snap2 "resources/samples/perc_snap2.wav")
(defsample perc_snap "resources/samples/perc_snap.wav")
(defsample perc_swash "resources/samples/perc_swash.wav")
(defsample perc_swoosh "resources/samples/perc_swoosh.wav")
(defsample perc_till "resources/samples/perc_till.wav")

;; Snares
(defsample sn_dolf "resources/samples/sn_dolf.wav")
(defsample sn_dub "resources/samples/sn_dub.wav")
(defsample sn_generic "resources/samples/sn_generic.wav")
(defsample sn_zome "resources/samples/sn_zome.wav")

;; Tabla
(defsample tabla_dhec "resources/samples/tabla_dhec.wav")
(defsample tabla_ghe1 "resources/samples/tabla_ghe1.wav")
(defsample tabla_ghe2 "resources/samples/tabla_ghe2.wav")
(defsample tabla_ghe3 "resources/samples/tabla_ghe3.wav")
(defsample tabla_ghe4 "resources/samples/tabla_ghe4.wav")
(defsample tabla_ghe5 "resources/samples/tabla_ghe5.wav")
(defsample tabla_ghe6 "resources/samples/tabla_ghe6.wav")
(defsample tabla_ghe7 "resources/samples/tabla_ghe7.wav")
(defsample tabla_ghe8 "resources/samples/tabla_ghe8.wav")
(defsample tabla_ke1 "resources/samples/tabla_ke1.wav")
(defsample tabla_ke2 "resources/samples/tabla_ke2.wav")
(defsample tabla_ke3 "resources/samples/tabla_ke3.wav")
(defsample tabla_na_o "resources/samples/tabla_na_o.wav")
(defsample tabla_na_s "resources/samples/tabla_na_s.wav")
(defsample tabla_na "resources/samples/tabla_na.wav")
(defsample tabla_re "resources/samples/tabla_re.wav")
(defsample tabla_tas1 "resources/samples/tabla_tas1.wav")
(defsample tabla_tas2 "resources/samples/tabla_tas2.wav")
(defsample tabla_tas3 "resources/samples/tabla_tas3.wav")
(defsample tabla_te1 "resources/samples/tabla_te1.wav")
(defsample tabla_te2 "resources/samples/tabla_te2.wav")
(defsample tabla_te_m "resources/samples/tabla_te_m.wav")
(defsample tabla_te_ne "resources/samples/tabla_te_ne.wav")
(defsample tabla_tun1 "resources/samples/tabla_tun1.wav")
(defsample tabla_tun2 "resources/samples/tabla_tun2.wav")
(defsample tabla_tun3 "resources/samples/tabla_tun3.wav")

;; Vinyl
(defsample vinyl_backspin "resources/samples/vinyl_backspin.wav")
(defsample vinyl_hiss "resources/samples/vinyl_hiss.wav")
(defsample vinyl_rewind "resources/samples/vinyl_rewind.wav")
